name: Canary

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: next
          fetch-depth: 0

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@automock'
          always-auth: true

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn
        run: yarn --frozen-lockfile && lerna bootstrap --ci

      - name: Build
        run: yarn build

      - name: Publish Canary
        run: lerna publish --yes --canary --preid dev --dist-tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}