name: Suites E2E

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'E2E Target Branch'
        required: true
defaults:
  run:
    working-directory: ./e2e

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        e2e-project: [ 'jest/nestjs', 'sinon/nestjs', 'vitest/nestjs', 'jest/inversify', 'sinon/inversify' ]
        node-version: [ 16.x, 18.x, 20.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Run Verdaccio Docker
        run: |
          docker run -d --name verdaccio \
          -p 4873:4873 \
          -v ${{ github.workspace }}/config.yaml:/verdaccio/conf/config.yaml \
          -v /path/to/your/storage:/verdaccio/storage \
          verdaccio/verdaccio

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: http://localhost:4873
          scope: '@suites'
          always-auth: true
          token: 'verdaccio-auth-token'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Registry Login
        run: npx npm-cli-login -s @suites -u test -p 1234 -e test@domain.test -r http://localhost:4873

      - name: Publish Packages
        run: |
          yarn lerna publish from-package --yes \
          --no-git-tag-version \
          --no-push \
          --no-changelog \
          --no-commit-hooks \
          --no-git-reset \
          --exact \
          --force-publish \
          --dist-tag e2e

      - name: Remove Source Code
        run: rm -rf packages

      - name: Setup and Test
        run: |
          IFS='/' read -r library framework <<< "${{ matrix.e2e-project }}"
          echo "FRAMEWORK=$framework" >> $GITHUB_ENV
          echo "LIBRARY=$library" >> $GITHUB_ENV

      - name: Execute Test
        run: |
          npm install --prefix "$PWD/e2e/$LIBRARY/$FRAMEWORK" --no-cache --no-package-lock
          npm test --prefix "$PWD/e2e/$LIBRARY/$FRAMEWORK"
        working-directory: ${{ github.workspace }}
