name: Semantic Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          types: |
            fix
            feat
            refactor
            ci
            docs
            test
            style
            chore
            pref
          scopes: |
            doubles.jest
            sinon
            jest
            types
            doubles.jest
            *
          wip: true
