name: Tag Version
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release Type'
        options:
          - 'graduate'
          - 'prerelease'
        required: true
        default: 'prerelease'
      target_branch:
        description: 'Target Branch'
        options:
          - 'master'
          - 'next'
        required: true
        default: 'next'
      preid:
        description: 'Prefix Id'
        options:
          - 'latest'
          - 'next'
          - 'rc'
          - 'dev'
          - 'alpha'
          - 'beta'
        required: true
        default: 'next'

jobs:
  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          fetch-depth: 0

      - name: Config Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Prerelease Version
        if: ${{ github.event.inputs.release_type == 'prerelease' }}
        run: |
          npx lerna version prerelease --yes \
          --preid ${{ github.event.inputs.preid }} \
          --no-git-tag-version --no-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Graduate Version
        if: ${{ github.event.inputs.release_type == 'graduate' }}
        run: npx lerna version graduate --yes --sign-git-tag --sign-git-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes to Branch
        run: |
          git push origin ${{ github.event.inputs.target_branch }}
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
