name: Packages Prerelease Version

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  version-packages:
    name: Version Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Config Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Yarn / Lerna
        run: |
          yarn --frozen-lockfile
          lerna bootstrap --ci

      - name: Version Packages
        run: |
          yarn lerna version \
          --yes --preid next \
          --conventional-commits \
          --conventional-prerelease
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create PR Comment
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.get-merged-pull-request.outputs.number }}
          body: |
            *New Version Released!* :tada: \
